import React, { useState, useEffect } from 'react'
import { Library, Executor, Repository } from 'cql-execution'
import { PatientSource } from 'cql-exec-fhir'
import { fhirService } from './fhir-service.js'

// =============================================================================
// ELM Libraries (compiled CQL)
// These are imported as JSON - compile with: tools/cql-translator
// =============================================================================
import BreastCancerScreeningELM from './elm/BreastCancerScreening.json'
import TobaccoScreeningELM from './elm/TobaccoScreening.json'
import CervicalCancerScreeningELM from './elm/CervicalCancerScreening.json'
import ColorectalCancerScreeningELM from './elm/ColorectalCancerScreening.json'
import FolicAcidSupplementationELM from './elm/FolicAcidSupplementation.json'
import OphthalmiaNeonatorumProphylaxisELM from './elm/OphthalmiaNeonatorumProphylaxis.json'
import HepatitisBScreeningPregnancyELM from './elm/HepatitisBScreeningPregnancy.json'
import HIVPreexposureProphylaxisELM from './elm/HIVPreexposureProphylaxis.json'
import HypertensionScreeningAdultELM from './elm/HypertensionScreeningAdult.json'
import RhdIncompatibilityELM from './elm/RhdIncompatibility.json'
import SyphilisScreeningELM from './elm/SyphilisScreening.json'
import HIVScreeningAgeELM from './elm/HIVScreeningAge.json'
import HIVScreeningPregnancyELM from './elm/HIVScreeningPregnancy.json'
import FHIRHelpersELM from './elm/FHIRHelpers.json'
// Note: QICoreCommon and Status are no longer needed after refactoring to FHIR R4 base types

const elmLibraries = {
  BreastCancerScreening: BreastCancerScreeningELM,
  TobaccoScreening: TobaccoScreeningELM,
  CervicalCancerScreening: CervicalCancerScreeningELM,
  ColorectalCancerScreening: ColorectalCancerScreeningELM,
  FolicAcidSupplementation: FolicAcidSupplementationELM,
  OphthalmiaNeonatorumProphylaxis: OphthalmiaNeonatorumProphylaxisELM,
  HepatitisBScreeningPregnancy: HepatitisBScreeningPregnancyELM,
  HIVPreexposureProphylaxis: HIVPreexposureProphylaxisELM,
  HypertensionScreeningAdult: HypertensionScreeningAdultELM,
  RhdIncompatibility: RhdIncompatibilityELM,
  SyphilisScreening: SyphilisScreeningELM,
  HIVScreeningAge: HIVScreeningAgeELM,
  HIVScreeningPregnancy: HIVScreeningPregnancyELM,
  FHIRHelpers: FHIRHelpersELM,
}

// =============================================================================
// ValueSet Code Service
// Generated by: tools/vsac-download/convert-valuesets.js
// =============================================================================
import { codeService } from './valuesets.js'

// =============================================================================
// Guideline Configuration
// Same structure as mock-emr for consistency
// =============================================================================
const GUIDELINE_CONFIG = {
  bcs: {
    libraryId: 'BreastCancerScreening',
    title: 'Breast Cancer Screening',
    getAlerts: (result) => {
      const recommend = result.RecommendMammogram
      return [{
        key: 'mammogram',
        active: recommend === true,
        activeText: 'Mammogram Recommended',
        inactiveText: 'No Mammogram Recommended',
      }]
    },
    getDetails: (result) => [
      { label: 'Gender', value: result.Gender },
      { label: 'Age in Years', value: result.AgeInYears },
      { label: 'Mammogram in Last Two Years', value: result.MammogramInLastTwoYears },
      { label: 'Has Bilateral Mastectomy', value: result.HasBilateralMastectomy },
      { label: 'Has Breast Cancer Diagnosis', value: result.HasBreastCancerDiagnosis },
    ],
  },
  tob: {
    libraryId: 'TobaccoScreening',
    title: 'Tobacco Cessation',
    getAlerts: (result) => {
      return [
        {
          key: 'record',
          active: result.RecordTobaccoUse === true,
          activeText: 'Record Tobacco Use Status',
          inactiveText: null,
        },
        {
          key: 'advise',
          active: result.AdviseToQuit === true,
          activeText: 'Advise Patient to Quit',
          inactiveText: null,
        },
        {
          key: 'pharmaco',
          active: result.OfferPharmacotherapy === true,
          activeText: 'Offer Pharmacotherapy (FDA-approved cessation medications)',
          inactiveText: null,
        },
        {
          key: 'behavioral',
          active: result.OfferBehavioralTherapy === true,
          activeText: 'Offer Behavioral Therapy',
          inactiveText: null,
        },
      ]
    },
    getDetails: (result) => [
      { label: 'Age in Years', value: result.AgeInYears },
      { label: 'Tobacco Use Status', value: result.TobaccoUseStatus },
      { label: 'Is Pregnant', value: result.IsPregnant },
      { label: 'Is Current Tobacco User', value: result.IsCurrentTobaccoUser },
    ],
  },
  ccs: {
    libraryId: 'CervicalCancerScreening',
    title: 'Cervical Cancer Screening',
    getAlerts: (result) => {
      const screeningDue = result.CervicalScreeningDue
      const screeningInterval = result.ScreeningInterval
      return [{
        key: 'screening',
        active: screeningDue === true,
        activeText: 'Cervical Screening Due',
        inactiveText: 'No Cervical Screening Due',
        tooltip: screeningInterval,
      }]
    },
    getDetails: (result) => [
      { label: 'Gender', value: result.Gender },
      { label: 'Age in Years', value: result.AgeInYears },
      { label: 'Screening Options', value: result.ScreeningInterval },
      { label: 'Cytology in Last 3 Years', value: result.HasCervicalCytologyInLastThreeYears },
      { label: 'hrHPV in Last 5 Years', value: result.HasHrHPVInLastFiveYears },
      { label: 'Absence of Cervix', value: result.HasAbsenceOfCervix },
      { label: 'Exclusion Reason', value: result.ExclusionReason },
    ],
  },
  crc: {
    libraryId: 'ColorectalCancerScreening',
    title: 'Colorectal Cancer Screening',
    getAlerts: (result) => {
      const screeningDue = result.ColorectalScreeningDue
      return [{
        key: 'screening',
        active: screeningDue === true,
        activeText: 'Colorectal Cancer Screening Due',
        inactiveText: 'No Colorectal Screening Due',
        tooltip: result.ScreeningOptions,
      }]
    },
    getDetails: (result) => [
      { label: 'Age in Years', value: result.AgeInYears },
      { label: 'Screening Options', value: result.ScreeningOptions },
      { label: 'FOBT in Last Year', value: result.HasFOBTInLastYear },
      { label: 'sDNA-FIT in Last 2 Years', value: result.HasDNAFITInLastTwoYears },
      { label: 'CT Colonography in Last 5 Years', value: result.HasCTColonographyInLastFiveYears },
      { label: 'Flex Sig in Last 5 Years', value: result.HasFlexSigInLastFiveYears },
      { label: 'Colonoscopy in Last 10 Years', value: result.HasColonoscopyInLastTenYears },
      { label: 'Has Total Colectomy', value: result.HasTotalColectomy },
      { label: 'Has Colorectal Cancer', value: result.HasColorectalCancer },
      { label: 'Exclusion Reason', value: result.ExclusionReason },
    ],
  },
  fol: {
    libraryId: 'FolicAcidSupplementation',
    title: 'Folic Acid Supplementation',
    getAlerts: (result) => {
      const recommend400 = result.RecommendFolicAcid400Mcg
      const recommend4mg = result.RecommendFolicAcid4Mg
      return [{
        key: 'folicacid',
        active: recommend400 === true || recommend4mg === true,
        activeText: result.RecommendationText || 'Folic Acid Supplementation Recommended',
        inactiveText: 'No Folic Acid Recommendation',
      }]
    },
    getDetails: (result) => [
      { label: 'Gender', value: result.Gender },
      { label: 'Age in Years', value: result.AgeInYears },
      { label: 'Is Eligible (Female 15-45)', value: result.IsEligible },
      { label: 'Recommend 400mcg', value: result.RecommendFolicAcid400Mcg },
      { label: 'Recommend 4mg', value: result.RecommendFolicAcid4Mg },
      { label: 'Exclusion Reason', value: result.ExclusionReason },
    ],
  },
  onp: {
    libraryId: 'OphthalmiaNeonatorumProphylaxis',
    title: 'Ophthalmia Neonatorum Prophylaxis',
    getAlerts: (result) => {
      return [{
        key: 'prophylaxis',
        active: result.AdministerOcularProphylaxis === true,
        activeText: result.RecommendationText || 'Administer Ocular Prophylaxis',
        inactiveText: 'No Prophylaxis Needed',
      }]
    },
    getDetails: (result) => [
      { label: 'Age in Days', value: result.AgeInDays },
      { label: 'Is Newborn (<=28 days)', value: result.IsNewborn },
      { label: 'Prophylaxis Administered', value: result.OcularProphylaxisAdministered },
      { label: 'Exclusion Reason', value: result.ExclusionReason },
    ],
  },
  hbv: {
    libraryId: 'HepatitisBScreeningPregnancy',
    title: 'Hepatitis B Screening (Pregnancy)',
    getAlerts: (result) => {
      return [{
        key: 'hbsag',
        active: result.PerformHBsAgScreening === true,
        activeText: result.RecommendationText || 'Order HBsAg Screening',
        inactiveText: 'No HBsAg Screening Needed',
      }]
    },
    getDetails: (result) => [
      { label: 'Gender', value: result.Gender },
      { label: 'Is Female', value: result.IsFemale },
      { label: 'Is Currently Pregnant', value: result.IsCurrentlyPregnant },
      { label: 'HBsAg Screening Performed', value: result.HBsAgScreeningPerformed },
      { label: 'Exclusion Reason', value: result.ExclusionReason },
    ],
  },
  prp: {
    libraryId: 'HIVPreexposureProphylaxis',
    title: 'HIV Pre-Exposure Prophylaxis (PrEP)',
    getAlerts: (result) => {
      return [{
        key: 'prep',
        active: result.PrescribePrEP === true,
        activeText: result.RecommendationText || 'Consider Prescribing PrEP',
        inactiveText: 'PrEP Not Indicated',
      }]
    },
    getDetails: (result) => [
      { label: 'Age in Years', value: result.AgeInYears },
      { label: 'Meets Age Requirement (>=13)', value: result.MeetsAgeRequirement },
      { label: 'Weight (kg)', value: result.WeightInKilo },
      { label: 'Meets Weight Requirement (>=35kg)', value: result.MeetsWeightRequirement },
      { label: 'HIV Negative', value: result.HIVNegative },
      { label: 'Is Eligible', value: result.IsEligible },
      { label: 'Has PrEP Indication', value: result.HasPrEPIndication },
      { label: 'Exclusion Reason', value: result.ExclusionReason },
    ],
  },
  htn: {
    libraryId: 'HypertensionScreeningAdult',
    title: 'Hypertension Screening',
    getAlerts: (result) => {
      return [{
        key: 'bp',
        active: result.OfficeBloodPressureMeasurement === true,
        activeText: result.RecommendationText || 'Measure Blood Pressure',
        inactiveText: 'No BP Measurement Needed',
      }]
    },
    getDetails: (result) => [
      { label: 'Age in Years', value: result.AgeInYears },
      { label: 'Is Adult (>=18)', value: result.IsAdult },
      { label: 'Is Age 40+', value: result.IsAge40Plus },
      { label: 'Is Age 18-39', value: result.IsAge18To39 },
      { label: 'Has Hypertension Diagnosis', value: result.DiagnosisOfHypertension },
      { label: 'BP in Last Year', value: result.OBPMBInTheLastYear },
      { label: 'BP in Last 4 Years', value: result.OBPMBInTheLast4Years },
      { label: 'At Increased Risk', value: result.AtIncreasedRisk },
      { label: 'Exclusion Reason', value: result.ExclusionReason },
    ],
  },
  rhd: {
    libraryId: 'RhdIncompatibility',
    title: 'Rh(D) Incompatibility Screening',
    getAlerts: (result) => {
      return [{
        key: 'rhd',
        active: result.PerformRhDAndAntibodyTests === true,
        activeText: result.RecommendationText || 'Order Rh(D) Typing and Antibody Screen',
        inactiveText: 'No Rh(D) Testing Needed',
      }]
    },
    getDetails: (result) => [
      { label: 'Is Currently Pregnant', value: result.IsCurrentlyPregnant },
      { label: 'Rh Typing Done', value: result.RhTypingDone },
      { label: 'Antibody Screen Done', value: result.AntibodyScreenDone },
      { label: 'Both Tests Done', value: result.RhDAndAntibodyScreenDone },
      { label: 'Exclusion Reason', value: result.ExclusionReason },
    ],
  },
  syp: {
    libraryId: 'SyphilisScreening',
    title: 'Syphilis Screening',
    getAlerts: (result) => {
      return [{
        key: 'syphilis',
        active: result.PerformSyphilisTesting === true,
        activeText: result.RecommendationText || 'Order Syphilis Screening',
        inactiveText: 'No Syphilis Screening Needed',
      }]
    },
    getDetails: (result) => [
      { label: 'Age in Years', value: result.AgeInYears },
      { label: 'Is Adolescent/Adult', value: result.AdolescentOrAdult },
      { label: 'Is Pregnant', value: result.Pregnant },
      { label: 'Is Asymptomatic', value: result.Asymptomatic },
      { label: 'At Increased Risk', value: result.AtIncreasedRisk },
      { label: 'Pregnancy Screening Done', value: result.PregnancyScreeningDone },
      { label: 'Exclusion Reason', value: result.ExclusionReason },
    ],
  },
  hiv: {
    libraryId: 'HIVScreeningAge',
    title: 'HIV Screening (Age-Based)',
    getAlerts: (result) => {
      return [{
        key: 'hiv',
        active: result.RecommendHIVTesting === true,
        activeText: result.RecommendationText || 'Order HIV Screening',
        inactiveText: 'No HIV Screening Needed',
      }]
    },
    getDetails: (result) => [
      { label: 'Age in Years', value: result.AgeInYears },
      { label: 'Is Universal Screening Age (15-65)', value: result.IsUniversalScreeningAge },
      { label: 'Is Under Screening Age (<15)', value: result.IsUnderScreeningAge },
      { label: 'Is Over Screening Age (>65)', value: result.IsOverScreeningAge },
      { label: 'Has HIV Test', value: result.HasHIVTest },
      { label: 'Has HIV Risk Factors', value: result.HasHIVRiskFactors },
      { label: 'Exclusion Reason', value: result.ExclusionReason },
    ],
  },
  hvp: {
    libraryId: 'HIVScreeningPregnancy',
    title: 'HIV Screening (Pregnancy)',
    getAlerts: (result) => {
      return [{
        key: 'hivpreg',
        active: result.PerformHIVTest === true,
        activeText: result.RecommendationText || 'Order HIV Screening (Prenatal)',
        inactiveText: 'No HIV Screening Needed',
      }]
    },
    getDetails: (result) => [
      { label: 'Is Pregnant', value: result.IsPregnant },
      { label: 'HIV Status', value: result.HIVStatus },
      { label: 'Has HIV Test This Pregnancy', value: result.HasHIVTestThisPregnancy },
      { label: 'Is First Prenatal Visit', value: result.IsFirstPrenatalVisit },
      { label: 'Is Third Trimester', value: result.IsThirdTrimester },
      { label: 'Has HIV Risk Factors', value: result.HasHIVRiskFactors },
      { label: 'Exclusion Reason', value: result.ExclusionReason },
    ],
  },
}

// =============================================================================
// CQL Execution Mode Configuration
// =============================================================================
// 'client' = JavaScript cql-execution (runs in browser)
// 'server' = HAPI $evaluate (Java CQL engine, 100% accurate)
const DEFAULT_CQL_MODE = 'client'

// Server URL for server-side CQL evaluation
// In production with nginx proxy: '/fhir' (same origin)
// For local development: 'http://localhost:8080/fhir'
const DEFAULT_CQL_SERVER_URL = '/fhir'

// =============================================================================
// Result Normalization (for client-side execution)
// =============================================================================
// cql-execution returns FHIR type wrappers (e.g., {value: "female"})
// while HAPI returns primitives directly. This normalizes to primitives.
function normalizeValue(value) {
  if (value === null || value === undefined) return value
  if (typeof value !== 'object') return value
  if (Array.isArray(value)) return value.map(normalizeValue)
  if ('value' in value) return normalizeValue(value.value)
  if ('code' in value) return value.code
  return value
}

function normalizeResults(results) {
  const normalized = {}
  for (const [key, value] of Object.entries(results)) {
    normalized[key] = normalizeValue(value)
  }
  return normalized
}

// =============================================================================
// CQL Execution Engine (Client-Side)
// =============================================================================
async function executeCqlLocally(libraryId, patientBundle) {
  const elmJson = elmLibraries[libraryId]
  if (!elmJson) {
    throw new Error(`ELM not loaded for library: ${libraryId}. Run the setup steps first.`)
  }

  // Build repository with all dependent libraries
  const repository = new Repository(Object.values(elmLibraries))

  // Create the main library
  const library = new Library(elmJson, repository)

  // Create executor with code service for ValueSet lookups
  const executor = new Executor(library, codeService)

  // Create FHIR R4 patient source
  const patientSource = PatientSource.FHIRv401()

  // Debug: log bundle structure
  console.log('Patient bundle:', JSON.stringify(patientBundle, null, 2).slice(0, 500))

  patientSource.loadBundles([patientBundle])

  // Execute CQL (exec returns a Promise)
  const results = await executor.exec(patientSource)

  // Debug: log full results structure
  console.log('CQL execution results:', results)
  console.log('patientResults:', results?.patientResults)
  console.log('unfilteredResults:', results?.unfilteredResults)

  // Extract patient ID
  const patientId = patientBundle.entry
    ?.find(e => e.resource?.resourceType === 'Patient')
    ?.resource?.id
  console.log('Looking for patientId:', patientId)

  // Try different result access patterns
  if (results?.patientResults) {
    console.log('patientResults keys:', Object.keys(results.patientResults))
    return results.patientResults[patientId] || {}
  }

  // Fallback: maybe results is the patient results directly
  if (results && typeof results === 'object' && !results.patientResults) {
    console.log('Using results directly')
    return results
  }

  return {}
}

// =============================================================================
// React App
// =============================================================================
function App() {
  const [patients, setPatients] = useState([])
  const [selectedPatientId, setSelectedPatientId] = useState('')
  const [selectedPatient, setSelectedPatient] = useState(null)
  const [cdsResults, setCdsResults] = useState([]) // Array of { guideline, result }
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState(null)
  const [executionTime, setExecutionTime] = useState(null)
  const [fhirReady, setFhirReady] = useState(false)
  const [launchMode, setLaunchMode] = useState(null) // 'standalone' or 'smart'
  const [cqlMode, setCqlMode] = useState(DEFAULT_CQL_MODE) // 'client' or 'server'

  // Check if ELM is loaded
  const elmLoaded = Object.keys(elmLibraries).length > 0

  // Initialize FHIR client on mount
  useEffect(() => {
    initFhirClient()
  }, [])

  // Fetch patients after FHIR client is ready (standalone mode only)
  useEffect(() => {
    if (fhirReady && launchMode === 'standalone') {
      fetchPatients()
    }
  }, [fhirReady, launchMode])

  // Evaluate CDS when patient is selected or CQL mode changes
  useEffect(() => {
    if (selectedPatientId) {
      evaluateCds(selectedPatientId)
    } else {
      setCdsResults([])
      setSelectedPatient(null)
      setExecutionTime(null)
    }
  }, [selectedPatientId, cqlMode])

  async function initFhirClient() {
    try {
      await fhirService.initAuto('/fhir')
      setFhirReady(true)
      setLaunchMode(fhirService.mode)

      // If SMART launch, try to get patient from context
      if (fhirService.mode === 'smart') {
        const contextPatient = await fhirService.getPatientFromContext()
        if (contextPatient) {
          setSelectedPatientId(contextPatient.id)
          setSelectedPatient(contextPatient)
        }
      }

      console.log(`[App] FHIR initialized: ${fhirService.mode} mode, server: ${fhirService.getServerUrl()}`)
    } catch (err) {
      setError('Failed to initialize FHIR client: ' + err.message)
    }
  }

  async function fetchPatients() {
    try {
      const tagBase = 'http://example.org/test-lifecycle'
      const guidelineTags = Object.keys(GUIDELINE_CONFIG).map(prefix => `${prefix}-test`)

      const patientList = await fhirService.fetchPatientsByTag(tagBase, guidelineTags)
      patientList.sort((a, b) => a.id.localeCompare(b.id))
      setPatients(patientList)
    } catch (err) {
      setError('Failed to fetch patients: ' + err.message)
    }
  }

  function getApplicableGuidelines(patient, bundle) {
    const applicable = []
    const age = getPatientAge(patient)
    const gender = patient.gender?.toLowerCase()

    // First, check for test tags (used with HAPI test patients)
    // If tagged, only return the tagged guideline
    const tags = patient.meta?.tag || []
    for (const tag of tags) {
      if (tag.system === 'http://example.org/test-lifecycle') {
        const prefix = tag.code?.split('-')[0]
        if (prefix && GUIDELINE_CONFIG[prefix]) {
          return [GUIDELINE_CONFIG[prefix]]
        }
      }
    }

    // For real patients: check eligibility for ALL guidelines

    // Breast Cancer Screening: female, age 40-74
    if (gender === 'female' && age >= 40 && age <= 74) {
      applicable.push(GUIDELINE_CONFIG.bcs)
    }

    // Cervical Cancer Screening: female, age 21-65
    if (gender === 'female' && age >= 21 && age <= 65) {
      applicable.push(GUIDELINE_CONFIG.ccs)
    }

    // Tobacco Screening: adults 18+
    if (age >= 18) {
      applicable.push(GUIDELINE_CONFIG.tob)
    }

    // Colorectal Cancer Screening: age 46-75
    if (age >= 46 && age <= 75) {
      applicable.push(GUIDELINE_CONFIG.crc)
    }

    // Folic Acid Supplementation: female, age 15-45
    if (gender === 'female' && age >= 15 && age <= 45) {
      applicable.push(GUIDELINE_CONFIG.fol)
    }

    // Ophthalmia Neonatorum Prophylaxis: newborns (age <= 28 days)
    // Age in days: if birthDate is within last 28 days
    if (age === 0) {
      applicable.push(GUIDELINE_CONFIG.onp)
    }

    // Hypertension Screening: adults 18+
    if (age >= 18) {
      applicable.push(GUIDELINE_CONFIG.htn)
    }

    // HIV Screening (Age-Based): ages 15-65 universal, or any age with risk factors
    if (age >= 15 && age <= 65) {
      applicable.push(GUIDELINE_CONFIG.hiv)
    }

    // HIV PrEP: age >= 13 (adolescents and adults)
    if (age >= 13) {
      applicable.push(GUIDELINE_CONFIG.prp)
    }

    // Syphilis Screening: adolescents/adults (age >= 12) with risk factors
    // For real patients, always include - CQL will determine if at-risk
    if (age >= 12) {
      applicable.push(GUIDELINE_CONFIG.syp)
    }

    // Pregnancy-specific guidelines: check bundle for active pregnancy Condition
    const isPregnant = bundle?.entry?.some(e => {
      const r = e.resource
      return r?.resourceType === 'Condition'
        && r?.code?.coding?.some(c => c.system === 'http://snomed.info/sct' && c.code === '77386006')
        && (r?.clinicalStatus?.coding?.[0]?.code === 'active' || !r?.clinicalStatus)
    })

    if (isPregnant) {
      applicable.push(GUIDELINE_CONFIG.hbv)
      applicable.push(GUIDELINE_CONFIG.rhd)
      applicable.push(GUIDELINE_CONFIG.hvp)
    }

    return applicable
  }

  async function evaluateCds(patientId) {
    setLoading(true)
    setError(null)
    setCdsResults([])
    setExecutionTime(null)

    try {
      // Fetch patient and build bundle using fhirService
      const bundle = await fhirService.buildPatientBundle(patientId)
      const patient = bundle.entry.find(e => e.resource?.resourceType === 'Patient')?.resource
      setSelectedPatient(patient)

      // Determine which guidelines apply to this patient
      const guidelines = getApplicableGuidelines(patient, bundle)
      if (guidelines.length === 0) {
        setError('No applicable CDS guidelines found for this patient')
        return
      }

      // Check if ELM is loaded (only needed for client-side mode)
      if (cqlMode === 'client' && !elmLoaded) {
        setError('ELM libraries not loaded. Complete the setup steps first.')
        return
      }

      // Execute CQL for ALL applicable guidelines in parallel
      const startTime = performance.now()
      const results = await Promise.all(
        guidelines.map(async (guideline) => {
          let result
          if (cqlMode === 'server') {
            // Server-side execution via HAPI $evaluate
            result = await fhirService.evaluateCqlOnServer(
              DEFAULT_CQL_SERVER_URL,
              guideline.libraryId,
              bundle
            )
          } else {
            // Client-side execution via cql-execution (JavaScript)
            const rawResult = await executeCqlLocally(guideline.libraryId, bundle)
            result = normalizeResults(rawResult)
          }
          return { guideline, result }
        })
      )
      const endTime = performance.now()
      setExecutionTime(Math.round(endTime - startTime))

      setCdsResults(results)
    } catch (err) {
      setError('Failed to evaluate CDS: ' + err.message)
    } finally {
      setLoading(false)
    }
  }

  function getPatientDisplayName(patient) {
    if (!patient) return ''
    const name = patient.name?.[0]
    if (name) {
      const given = name.given?.join(' ') || ''
      const family = name.family || ''
      return `${given} ${family}`.trim() || patient.id
    }
    return patient.id
  }

  function getPatientAge(patient) {
    if (!patient?.birthDate) return null
    const [year, month, day] = patient.birthDate.split('-').map(Number)
    const birth = new Date(year, month - 1, day)
    const today = new Date()
    let age = today.getFullYear() - birth.getFullYear()
    const monthDiff = today.getMonth() - birth.getMonth()
    if (monthDiff < 0 || (monthDiff === 0 && today.getDate() < birth.getDate())) {
      age--
    }
    return age
  }

  // Helper to render a single CDS card
  function renderCdsCard({ guideline, result }) {
    const alerts = guideline.getAlerts(result)
    const activeAlerts = alerts.filter(a => a.active || a.inactiveText)
    const hasPositiveRecommendation = alerts.some(a => a.active)

    return (
      <section
        key={guideline.libraryId}
        className={`cds-card ${hasPositiveRecommendation ? 'recommend' : 'no-recommend'}`}
      >
        <h2>CDS Recommendation: {guideline.title}</h2>

        {activeAlerts.length === 0 && (
          <div className="recommendation">
            <span className="icon">-</span>
            <span className="text">No Action Required</span>
          </div>
        )}

        {activeAlerts.map(alert => (
          <div key={alert.key} className="recommendation">
            {alert.active ? (
              <>
                <span className="icon">+</span>
                <span className="text">{alert.activeText}</span>
              </>
            ) : (
              <>
                <span className="icon">-</span>
                <span className="text">{alert.inactiveText}</span>
              </>
            )}
          </div>
        ))}

        <details className="cds-details">
          <summary>View Decision Factors</summary>
          <dl>
            {guideline.getDetails(result).map(({ label, value }) => (
              <React.Fragment key={label}>
                <dt>{label}</dt>
                <dd>{String(value ?? 'N/A')}</dd>
              </React.Fragment>
            ))}
          </dl>
        </details>
      </section>
    )
  }

  return (
    <div className="app">
      <header className="header">
        <h1>
          USPSTF Clinical Decision Support
          <span className="mode-badge">
            {launchMode === 'smart' ? 'SMART Launch' : 'Standalone'}
          </span>
        </h1>
        <p className="subtitle">
          {fhirReady
            ? `Connected to: ${fhirService.getServerUrl()}`
            : 'Initializing FHIR client...'}
        </p>
        <div className="cql-mode-toggle">
          <label>
            CQL Engine:
            <select
              value={cqlMode}
              onChange={(e) => setCqlMode(e.target.value)}
            >
              <option value="client">Client (JavaScript)</option>
              <option value="server">Server (HAPI Java)</option>
            </select>
          </label>
          <span className="cql-mode-info">
            {cqlMode === 'server'
              ? 'Using HAPI $evaluate (100% accurate)'
              : 'Using cql-execution (browser)'}
          </span>
        </div>
      </header>

      <main className="main">
        {!elmLoaded && (
          <div className="error-card">
            <strong>Setup Required:</strong> ELM libraries not loaded.
            <br /><br />
            Run these commands:
            <pre style={{ marginTop: '0.5rem', fontSize: '0.8rem' }}>
{`# 1. Compile CQL to ELM
cd tools/cql-translator
sdk use java 21.0.6-tem
mvn exec:java -q -Dexec.args="..."

# 2. Copy ELM to smart-app/src/elm/

# 3. Uncomment imports in App.jsx`}
            </pre>
          </div>
        )}

        {/* Patient selector - shown in standalone mode or if SMART launch has no patient */}
        {launchMode === 'standalone' && (
          <section className="patient-selector">
            <label htmlFor="patient-select">Select Patient:</label>
            <select
              id="patient-select"
              value={selectedPatientId}
              onChange={(e) => setSelectedPatientId(e.target.value)}
              disabled={!fhirReady}
            >
              <option value="">-- Select a patient --</option>
              {patients.map(patient => (
                <option key={patient.id} value={patient.id}>
                  {patient.id}
                </option>
              ))}
            </select>
          </section>
        )}

        {launchMode === 'smart' && selectedPatient && (
          <div className="smart-context-info">
            Patient from EHR context: <strong>{selectedPatient.id}</strong>
          </div>
        )}

        {error && (
          <div className="error-card">
            {error}
          </div>
        )}

        {loading && (
          <div className="loading">
            Evaluating CDS {cqlMode === 'server' ? 'via HAPI server' : 'locally'}...
          </div>
        )}

        {executionTime !== null && !loading && (
          <div className="execution-info">
            CQL executed in <code>{executionTime}ms</code>
            {cqlMode === 'server'
              ? ' (server-side via HAPI $evaluate)'
              : ' (client-side, no server round-trip)'}
          </div>
        )}

        {selectedPatient && !loading && (
          <section className="patient-info">
            <h2>Patient Information</h2>
            <dl>
              <dt>ID</dt>
              <dd>{selectedPatient.id}</dd>
              <dt>Name</dt>
              <dd>{getPatientDisplayName(selectedPatient)}</dd>
              <dt>Gender</dt>
              <dd>{selectedPatient.gender || 'Unknown'}</dd>
              <dt>Birth Date</dt>
              <dd>{selectedPatient.birthDate || 'Unknown'}</dd>
              <dt>Age</dt>
              <dd>{getPatientAge(selectedPatient) ?? 'Unknown'} years</dd>
            </dl>
          </section>
        )}

        {cdsResults.length > 0 && !loading && (
          <div className="cds-cards">
            {cdsResults.map(renderCdsCard)}
          </div>
        )}
      </main>

      <footer className="footer">
        <p>SMART on FHIR + Local CQL Execution Demo</p>
      </footer>
    </div>
  )
}

export default App
